### ISSUE TITLE
The db breaks with certain types of keys (encoding issues?)

### ISSUE THREAD

**Issue by ykdojo** [replit/replit-py#49] opened 2021-03-08 01:48 UTC
Here's the repl that shows this bug: https://replit.com/@ykdojo/bug-report#main.py

When you do:

```
from replit import db
db['%E2'] = 3
print("db['%E2']: ", db['%E2'])
```

You get:
```
raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://kv.replit.com/v0/eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2MTUyNzg5ODYsImlhdCI6MTYxNTE2NzM4NiwiaXNzIjoiY29ubWFuIiwiZGF0YWJhc2VfaWQiOiIwMDNjMDIyNC03NjAzLTRkMDUtODk5Zi1iYzEzNTg3NWJiMzcifQ.NXV7go-7vWy5A7RTC0XMjF0JqhAyrAJElst_Pd5dWRjxoLC3d-wrXe_ftKScf1I_m5GZrVUl2abkBPGt6LufAA/%E2
```

**Comment by Scoder12** [comment] 2021-03-08 03:19
Thank you so much for this thoughtful bug report. I can confirm the bug on the latest release but not on master. That's good news because it means the bug is already fixed, although it is not published yet. I will try to get around to publishing the next major release ASAP so that this doesn't happen, but I need to fix a few things before the code is ready to be published, so that could take some time. 

For now you have two workaround options:
1. You can install the latest master in your repl by opening the shell and typing `poetry add git+https://github.com/replit/replit-py.git`.  This will tell poetry to install replit from this github repo instead of the latest release. 
2. You can escape the keys yourself using base64 or `urllib.parse.quote`. 

Since this is already fixed, I am going to close this issue, but feel free to comment if you have any further thoughts.

**Closed by Scoder12** 2021-03-08 03:19 UTC
